// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBsRYlsgreARVYJWqeoMYJ4kqPs3h4k0c',
    appId: '1:620889092539:web:3a203e7b13e9766de0149e',
    messagingSenderId: '620889092539',
    projectId: 'point-of-sale-30554',
    authDomain: 'point-of-sale-30554.firebaseapp.com',
    storageBucket: 'point-of-sale-30554.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTcr274dyNTv1GAmxdhK97OK7EnTXdSe0',
    appId: '1:620889092539:android:7db6da568e2dba1de0149e',
    messagingSenderId: '620889092539',
    projectId: 'point-of-sale-30554',
    storageBucket: 'point-of-sale-30554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCarEQI-Te8JV6fxN7e9ij0XYKkrUjWDVY',
    appId: '1:620889092539:ios:2e2a02f07ff657fae0149e',
    messagingSenderId: '620889092539',
    projectId: 'point-of-sale-30554',
    storageBucket: 'point-of-sale-30554.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCarEQI-Te8JV6fxN7e9ij0XYKkrUjWDVY',
    appId: '1:620889092539:ios:2e2a02f07ff657fae0149e',
    messagingSenderId: '620889092539',
    projectId: 'point-of-sale-30554',
    storageBucket: 'point-of-sale-30554.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBsRYlsgreARVYJWqeoMYJ4kqPs3h4k0c',
    appId: '1:620889092539:web:e4ea9171b27124bfe0149e',
    messagingSenderId: '620889092539',
    projectId: 'point-of-sale-30554',
    authDomain: 'point-of-sale-30554.firebaseapp.com',
    storageBucket: 'point-of-sale-30554.firebasestorage.app',
  );
}
